site_name: Pyr0-Piezo
site_description: Documentation for the Pyr0-Piezo Z-probe sensor
site_author: Alan "pyr0ball" Weinstock
repo_url: https://github.com/pyr0ball/pyr0piezo/

theme:
  name: 'material'
  logo: 'assets/images/Pyr0ball-logo.png'
  favicon: 'assets/images/Pyr0ball-logo.png'
  custom_dir: 'mkdocs-theme-overrides'

markdown_extensions:
  #http://pythonhosted.org/Markdown/extensions/admonition.html
  - admonition:
  - toc:
      permalink: True

nav:
  - 'Home': 'index.md'
  - 'About': 'about.md'
  - 'FAQ': 'faq.md'
  - 'Installation':
    - 'Start Here': 'installation.md'
    - 'Wiring Diagrams':
      - 'Creality 1284P': 'tutorials/wiring/creality-1284.md'
      - 'Duet Wifi': 'tutorials/wiring/duet-wifi.md'
      - 'MKS Family':
        - 'MKS Base 1.4': 'tutorials/wiring/mks-base.md'
        - 'MKS Gen L': 'tutorials/wiring/mks-gen-l.md'
        - 'MKS SBase': 'tutorials/wiring/mks-sbase.md'
      - 'RAMPS 1.4': 'tutorials/wiring/ramps-1.4.md'
    - 'Printer Specific':
      - 'Core XY':
        - 'Hypercube Evo (On Head)': 'mounts/core-xy/hevo-on-head.md'
      - 'Creality Family':
        - 'CR-10 Family': 'mounts/creality/creality-original-head.md'
        - 'Ender 3 Family': 'mounts/creality/creality-original-head.md'
      - 'Delta':
        - 'Monoprice Delta Mini': 'mounts/delta/monoprice-delta-mini.md'
        - 'On Head': 'mounts/delta/delta-head.md'
        - 'Under Bed': 'mounts/delta/delta-under-bed.md'
      - 'Deltesian': 'mounts/deltesian/deltesian.md'
      - 'Mendel':
        - 'On Head': 'mounts/mendel/mendel-on-head.md'
        - 'Gantry Mount': 'mounts/mendel/mendel-gantry-mount.md'
      - 'Prusa Mendel':
        - 'Prusa i3 on Head': 'mounts/prusa-mendel/i3-on-head.md'
        - 'HICTOP i3': 'mounts/prusa-mendel/hictop-i3.md'
      - 'Quadrap':
        - 'Makerbot Original Under Bed': 'mounts/quadrap/makerbot-under-bed.md'
        - 'Ultimaker Under Bed': 'mounts/quadrap/um-under-bed.md'
  - 'Configuration':
    - 'Pyr0-Piezo Config': 'config.md'
    - 'Printer Firmware Config':
      - 'Marlin': 'tutorials/config/printer-firmware/marlin/marlin-config.md'
      - 'Klipper': 'tutorials/config/printer-firmware/klipper/klipper-config.md'
  - 'Resources':
    - 'Schematics':
      - 'EasyPiezi': 'schematics/easypiezi/easypiezi-schematics.md'
      - 'FFC Direct Extruder': 'schematics/ffc-direct-extruder/ffc-direct-extruder-schematics.md'
      - 'FFC Direct Breakout': 'schematics/ffc-direct-breakout/ffc-direct-breakout-schematics.md'
    - 'Drawings':
      - 'Board Layouts':
        - 'EasyPiezi': 'drawings/layouts/easypiezi/easypiezi-layouts.md'
        - 'FFC Direct Extruder':
          - 'FFC Direct Extruder 1.1.0 Top': 'drawings/layouts/ffc-direct-extruder/Pyr0-Piezo_FFC_Extruder_Boardv1.1.0_Components_Front.pdf'
        #- 'FFC Direct Breakout':
      - 'Connector Pinouts':
        - 'EasyPiezi': 'drawings/pinouts/easypiezi/easypiezi-pinouts.md'
        - 'FFC Direct Extruder': 'drawings/pinouts/ffc-direct-extruder/ffc-direct-extruder-pinouts.md'
        - 'FFC Direct Breakout': 'drawings/pinouts/ffc-direct-breakouts/ffc-direct-breakout-pinouts.md'
      - 'Test Pads Layout': 'drawings/pyro-piezo-test-pads.md'
    - Changelog:
      - Version List: 'changelog.md'
      - Logs:
        - 'v2.1.3-v2.1.4': 'changelogs/changelog_2019-09-25_v2.1.3_v2.1.4.md'
        - 'v2.1.2-v2.1.3': 'changelogs/changelog_2019-09-25_v2.1.2_v2.1.3.md'
        - 'v2.1.1-v2.1.2': 'changelogs/changelog_2019-08-15_v2.1.1_v2.1.2.md'
        - 'v2.0.2-v2.1.1': 'changelogs/changelog_2019-08-15_v2.0.2_v2.1.1.md'
        - 'v2.0.1_hw-v2.0.2': 'changelogs/changelog_2019-08-15_v2.0.1_hw_v2.0.2.md'
        - 'v2.0.1-v2.0.1_hw': 'changelogs/changelog_2019-08-15_v2.0.1_v2.0.1_hw.md'
        - 'v2.0.0-v2.0.1': 'changelogs/changelog_2019-08-15_v2.0.0_v2.0.1.md'
        - '76b4ba6-v2.0.0': 'changelogs/changelog_2019-08-15_76b4ba6_v2.0.0.md'
        - 'cfa0abc-76b4ba6': 'changelogs/changelog_2019-08-15_cfa0abc_76b4ba6.md'
        - '551fcb7-cfa0abc': 'changelogs/changelog_2019-08-15_551fcb7_cfa0abc.md'

  - 'Main Site': 'https://pyroballpcbs.com'

google_analytics: ['UA-135668867-1', 'pyroballpcbs.com']
